// SPDX-FileCopyrightText: 2023 SAP SE
//
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of FEDEM - https://openfedem.org
////////////////////////////////////////////////////////////////////////////////

#ifndef FFL_INIT_H
#define FFL_INIT_H
#define FFL_INIT_ONLY
#include "FFlLib/FFlFEParts/FFlAllFEParts.H"
#include "FFlLib/FFlIOAdaptors/FFlAllIOAdaptors.H"
#undef FFL_INIT_ONLY
#undef FFL_ALL_FE_PARTS_H
#undef FFL_ALL_IO_ADAPTORS_H
#endif
