// SPDX-FileCopyrightText: 2023 SAP SE
//
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of FEDEM - https://openfedem.org
////////////////////////////////////////////////////////////////////////////////

/*!
  \file FFaBasicOperations.H
  \brief Implementation of operations for the basic algebra types.
  \author Jacob Storen
*/

#ifndef FFA_BASIC_OPERATIONS_H
#define FFA_BASIC_OPERATIONS_H

namespace FFa
{
  //! \brief Initializes operations on basic algebra types.
  void initBasicOps();
};

#endif
